version: '3'

dotenv:
  - .env

tasks:
  # prepare:
  #   cmd: go mod tidy

  # lint:
  #   cmds:
  #     - golangci-lint run ./cmd

  # test:
  #   cmds:
  #     - go test -cover ./cmd

  # compile:
  #   cmd: GOOS=linux go build -o ./bin/goapp ./goapp

  build:
    cmds: 
      - docker build --pull --rm -f 'appinfo.Dockerfile' -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:latest '.'
      - docker build --pull --rm -f 'appapi.Dockerfile' -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:latest '.'
      - docker build --pull --rm -f 'applogin.Dockerfile' -t ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:latest '.'

  push:
    cmds:
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:${APP_IMAGE_TAG}
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:${APP_IMAGE_TAG}
      - docker tag ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:latest ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:${APP_IMAGE_TAG}
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME1}:latest
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME2}:latest
      - docker push ${APP_IMAGE_OWNER}/${APP_IMAGE_NAME3}:latest

  deploy:
    cmds:
      - kubectl create namespace sirius
      - kubectl apply -f config-env-api.yaml -n sirius
      - kubectl apply -f config-env-info.yaml -n sirius
      - kubectl apply -f config-env-login.yaml -n sirius
      - kubectl apply -f deployment.yaml -n sirius
      - kubectl apply -f service.yaml -n sirius
      - kubectl apply -f ingress.yaml -n sirius
  commit:
    cmds:
      - git add .
      - git commit -m "vse2.0"
      - git push 


  release:
    cmds:
      #- task: prepare
      #- task: lint
      #- task: test
      #- task: compile
      - task: build
      - task: push
      - task: deploy
      - task: commit